version: "3.9"
services:
  api:
    build: .
    environment:
      - APP_PORT=8081
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=wallet_notifier
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - ETH_WS_URL=${ETH_WS_URL}
      - BITCOIN_RPC_URL=${BITCOIN_RPC_URL}
      - BITCOIN_RPC_USER=${BITCOIN_RPC_USER}
      - BITCOIN_RPC_PASS=${BITCOIN_RPC_PASS}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "8081:8081"
    depends_on:
      - mongo
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db


volumes:
  mongo_data: {}


